import "@hotwired/turbo-rails";
import { Application } from "@hotwired/stimulus";
import AutoscrollController from "./controllers/autoscroll_controller";
import ComposerController from "./controllers/composer_controller";
import StickyDetailsController from "./controllers/sticky_details_controller";
import DropdownController from "./controllers/dropdown_controller";
import MenuController from "./controllers/menu_controller";
import SidebarController from "./controllers/sidebar_controller";
import CommandController from "./controllers/command_controller";
import WorkflowController from "./controllers/workflow_controller";

const application = Application.start();
application.register("autoscroll", AutoscrollController);
application.register("composer", ComposerController);
application.register("sticky-details", StickyDetailsController);
application.register("dropdown", DropdownController);
application.register("menu", MenuController);
application.register("sidebar", SidebarController);
application.register("command", CommandController);
application.register("workflow", WorkflowController);
window.RbrunStimulus = application;
