import "@hotwired/turbo-rails";
import "./turbo_confirm"; // patches Turbo.config.forms.confirm → the styled <dialog id="confirm-dialog">
import { Application } from "@hotwired/stimulus";
import AutoscrollController from "./controllers/autoscroll_controller";
import ComposerController from "./controllers/composer_controller";
import StickyDetailsController from "./controllers/sticky_details_controller";
import DropdownController from "./controllers/dropdown_controller";
import MenuController from "./controllers/menu_controller";
import SidebarController from "./controllers/sidebar_controller";
import CommandController from "./controllers/command_controller";
import WorkflowController from "./controllers/workflow_controller";
import DrawerController from "./controllers/drawer_controller";
import OverlayController from "./controllers/overlay_controller";
import SearchBarController from "./controllers/search_bar_controller";
import OptionFilterController from "./controllers/option_filter_controller";
import BulkSelectController from "./controllers/bulk_select_controller";
import DropzoneController from "./controllers/dropzone_controller";
import SingleUploadController from "./controllers/single_upload_controller";
import RichTextAreaController from "./controllers/rich_text_area_controller";
import NestedForm from "@stimulus-components/rails-nested-form";
import RepoBadgeController from "./controllers/repo_badge_controller";
import RepoChoicesController from "./controllers/repo_choices_controller";

const application = Application.start();
application.register("autoscroll", AutoscrollController);
application.register("composer", ComposerController);
application.register("sticky-details", StickyDetailsController);
application.register("dropdown", DropdownController);
application.register("menu", MenuController);
application.register("sidebar", SidebarController);
application.register("command", CommandController);
application.register("workflow", WorkflowController);
application.register("drawer", DrawerController);
application.register("overlay", OverlayController);
application.register("search-bar", SearchBarController);
application.register("option-filter", OptionFilterController);
application.register("bulk-select", BulkSelectController);
application.register("dropzone", DropzoneController);
application.register("single-upload", SingleUploadController);
application.register("rich-text-area", RichTextAreaController);
application.register("nested-form", NestedForm);
application.register("repo-badge", RepoBadgeController);
application.register("repo-choices", RepoChoicesController);
window.RbrunStimulus = application;
